### ISSUE TITLE
1.07後的建議(?)

### ISSUE THREAD

**Issue by Acolyroce** [GniN/turtle-helper#1]
推文自動換行可能可以多一點自訂微調選項？

例如：

- 該板有沒有記錄IP。
- 自己的ID長度為多少。（或這板有沒有開推文會推齊）

以此為依據來算多少字換行，可以更有效利用一次推文的長度(?)

目前以9字ID、不記錄IP推文的狀況，半形字45字換行，全行字卻15字就換行了，感覺換行太快了。
同樣條件，半形字推文最大可以達到51字，全形字可以達到25字。
主要是全形字的換行差太多，滿虧的(?)，感覺這方面可以再調整！

**Comment by GniN** [comment]
該板有沒有記錄IP 這個不確定怎麼判斷，就不做了
1.08板會針對ID長度去調整推文長度，中文的推文字數有問題的問題已經修正
